In [60]:
import numpy as np
y = np.array([1,2,1,3,1,4,4,4,4,5])
count = np.bincount(y)
print(count)
print(np.argmax(count))
print(np.where(y == np.argmax(count))[0][0])

from scipy.stats import mode
m = mode(y)[0][0]
indice = np.where(y == m)[0][0]
print(m)
print(indice)
print(y[indice])

x = np.array([[1,2,3,4,5],[2,3,4,5,6]])
z = np.ones((3,5))
z[0,1] = 3
z[1,1] = 2
pre = np.dot(x,z.T)
xs = np.square(x)
zs = np.square(z)
prex = np.sum(xs,axis = 1)[:,np.newaxis]
prez = np.sum(zs,axis = 1)


print(prez)
print(prex)
print(prex + prez - pre)


[0 3 1 1 4 1]
4
5
4
5
4
[ 13.   8.   5.]
[[55]
 [90]]
[[ 49.  46.  45.]
 [ 77.  75.  75.]]
